### ISSUE TITLE
Releases 中是7621的固件，大佬文件名弄错了？

### ISSUE THREAD

**Issue by user1121114685** [insChow/Actions-OpenWrt#2]

**Comment by iplcdn** [comment]
极路由4的hc5962就是mt7621

**Comment by iplcdn** [comment]
![Uploading 34874687-FFC0-42A9-B444-B9E5EA474213.png…]()

**Comment by iplcdn** [comment]
![2AE0E874-5D38-4AA4-BC2C-5CE4A23E0C8D](https://user-images.githubusercontent.com/58213711/106311111-92f84b80-629f-11eb-84f0-6ea6322b44ac.png)

**Comment by iplcdn** [comment]
![Uploading 84111446-4158-4EF2-8F6C-5E5429B329FB.png…]()

**Comment by iplcdn** [comment]
![Uploading 4D6DABC4-BA84-47C5-A941-6EDC29DA9AD0.png…]()

**Comment by user1121114685** [comment]
x86_x64也编译一份撒

**Comment by iplcdn** [comment]
Releases中的就有x86_64的

**Comment by user1121114685** [comment]
> Releases中的就有x86_64的

并没有。。大佬

**Comment by insChow** [comment]
因为actions编译报错了，没有生成固件，需要调整config配置

**Comment by insChow** [comment]
![320E2B37-FFC9-4026-BE8E-90A6EC2E548B](https://user-images.githubusercontent.com/58213711/107894179-c0184f80-6f69-11eb-968a-096ed4f9da10.png)
